### ISSUE TITLE
 Missing base file in models folder

### ISSUE THREAD

**Issue by linlany** [iSEE-Laboratory/Revisting_FSCIL#1]
Hi,
thank you for your excellent work. 

I noticed that the models folder in this repository is missing the base file. This file seems to be essential for the proper functioning of the code. Could you please add the missing base file or provide guidance on how to proceed without it?

There is the logs: 
File "/Revisting_FSCIL-main/models/my_vit/fscil_trainer.py", line 3, in <module>
    from models.base.fscil_trainer import FSCILTrainer as Trainer
ModuleNotFoundError: No module named 'models.base'

**Comment by TOM-tym** [comment]
Hello, Thank you for your interest in our work!
Sorry for the inconvenience. I have uploaded the necessary files in commit 34546cc and checked it is now runnable.

I am going to close this issue now. If you have any further questions, please do not hesitate to reopen this or raise another issue.

Thank you for your attention and interest again.
